"""empty message

Revision ID: 80b179b08542
Revises: 
Create Date: 2021-06-24 14:57:24.259352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80b179b08542'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mappings_bp_gp',
    sa.Column('created_on', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_on', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('point_uuid', sa.String(length=80), nullable=False),
    sa.Column('mapped_point_uuid', sa.String(), nullable=False),
    sa.Column('point_name', sa.String(length=80), nullable=False),
    sa.Column('mapped_point_name', sa.String(length=80), nullable=False),
    sa.Column('mapping_state', sa.Enum('MAPPED', 'BROKEN', name='mappingstate'), nullable=True),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('mapped_point_uuid')
    )
    op.create_table('mappings_lp_gbp',
    sa.Column('created_on', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_on', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('point_uuid', sa.String(), nullable=False),
    sa.Column('mapped_point_uuid', sa.String(length=80), nullable=True),
    sa.Column('point_name', sa.String(length=80), nullable=False),
    sa.Column('mapped_point_name', sa.String(length=80), nullable=True),
    sa.Column('type', sa.Enum('GENERIC', 'BACNET', name='maptype'), nullable=True),
    sa.Column('mapping_state', sa.Enum('MAPPED', 'BROKEN', name='mappingstate'), nullable=True),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('mapped_point_uuid')
    )
    op.create_table('mappings_mp_gbp',
    sa.Column('created_on', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_on', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('uuid', sa.String(), nullable=False),
    sa.Column('point_uuid', sa.String(), nullable=False),
    sa.Column('mapped_point_uuid', sa.String(length=80), nullable=True),
    sa.Column('point_name', sa.String(length=80), nullable=False),
    sa.Column('mapped_point_name', sa.String(length=80), nullable=True),
    sa.Column('type', sa.Enum('GENERIC', 'BACNET', name='maptype'), nullable=True),
    sa.Column('mapping_state', sa.Enum('MAPPED', 'BROKEN', name='mappingstate'), nullable=True),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('mapped_point_uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mappings_mp_gbp')
    op.drop_table('mappings_lp_gbp')
    op.drop_table('mappings_bp_gp')
    # ### end Alembic commands ###
